<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/cocktails.css">

    <!-- ICONS : FontAwesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
</head>

<body class="container">
    <nav">
        <h1>
            <i class="fas fa-glass-martini-alt"></i>
            Mister Cocktail - Backoffice
            <i class="fas fa-glass-martini-alt"></i>
            <?php include 'inc/nav.phtml'; ?>
        </h1>
        </nav>

        
        <hr style="height: 2px; background-color: white">

<main class="row">
    <div class="col-12">
    <?= $messageSession; ?>
        <table class="table table-striped table-light">
            <thead class="thead-dark">
                <tr>
                    <th>#</th>
                    <th>Nom</th>
                    <th>Photo</th>
                    <th>Famille</th>
                    <th>Modifier</th>
                    <th>Supprimer</th>
                </tr>
            </thead>
            <thbody>
                <?php foreach ($listerCocktailsBO as $CocktailsBO) {?>
                <tr>
                <th><?= $CocktailsBO['id'] ?></th>
                <th><?= $CocktailsBO['nom'] ?></th>
                <th><img src="assets/images/cocktails/<?= $CocktailsBO['urlPhoto'] ?>" alt="image cocktail" width="150"></th>
                <th><?= $CocktailsBO['nomFamille'] ?></th>
                <th>
                    <a href="editionCocktail.php?action=modifier&id=<?=$CocktailsBO['id']?>">
                    <i class="fas fa-edit fa-2x"></i></a></th>
                <th>
                    <a class ="btnDelete" href="?action=supprimer&id=<?=$CocktailsBO['id']?>">
                    <i class="fas fa-trash-alt fa-2x"></i></a></th>
                <?php }?>
                </tr>
            </thbody>        
        </table>

        

    </div>
</main>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script src="assets/js/script.js"></script>
</body>


</html>